<section class="privacy">
    <article class="privacy_article">
        <h2 class="privacy_h2">Condizioni d'uso</h2>
        <p class="privacy_p">Un cookie è una piccola quantità di dati inviati al tuo browser da un server web e che vengono successivamente memorizzati sul disco fisso del tuo computer. Il cookie viene poi riletto e riconosciuto dal sito web che lo ha inviato ogni qualvolta effettui una connessione successiva. Come parte dei servizi personalizzati per i suoi utenti, il nostro sito utilizza dei cookie per memorizzare e talvolta tenere traccia di alcuni dei dati personali forniti dagli utenti stessi. Ti ricordiamo che il browser è quel software che ti permette di navigare velocemente nella Rete tramite la visualizzazione e il trasferimento delle informazioni sul disco fisso del tuo computer. Se le preferenze del tuo browser sono settate in modo da accettare i cookie, qualsiasi sito web può inviare i suoi cookie al tuo browser, ma – al fine di proteggere la tua privacy – può rilevare solo ed esclusivamente quelli inviati dal sito stesso, e non quelli invece inviati al tuo browser da altri siti. Se vuoi saperne di più poi consultare la nostra privacy policy qui. Puoi accettare i cookies e proseguire, oppure puoi configurare i singoli cookies, utilizzando i tasti qui sotto.</p>
    </article>
    <article class="privacy_article">
        <h2 class="privacy_h2">Cookie Policy</h2>
        <p class="privacy_p">Un cookie è una piccola quantità di dati inviati al tuo browser da un server web e che vengono successivamente memorizzati sul disco fisso del tuo computer. Il cookie viene poi riletto e riconosciuto dal sito web che lo ha inviato ogni qualvolta effettui una connessione successiva. Come parte dei servizi personalizzati per i suoi utenti, il nostro sito utilizza dei cookie per memorizzare e talvolta tenere traccia di alcuni dei dati personali forniti dagli utenti stessi. Ti ricordiamo che il browser è quel software che ti permette di navigare velocemente nella Rete tramite la visualizzazione e il trasferimento delle informazioni sul disco fisso del tuo computer. Se le preferenze del tuo browser sono settate in modo da accettare i cookie, qualsiasi sito web può inviare i suoi cookie al tuo browser, ma – al fine di proteggere la tua privacy – può rilevare solo ed esclusivamente quelli inviati dal sito stesso, e non quelli invece inviati al tuo browser da altri siti. Se vuoi saperne di più poi consultare la nostra privacy policy qui. Puoi accettare i cookies e proseguire, oppure puoi configurare i singoli cookies, utilizzando i tasti qui sotto. Se le preferenze del tuo browser sono settate in modo da accettare i cookie, qualsiasi sito web può inviare i suoi cookie al tuo browser, ma – al fine di proteggere la tua privacy – può rilevare solo ed esclusivamente quelli inviati dal sito stesso, e non quelli invece inviati al tuo browser da altri siti. Se vuoi saperne di più poi consultare la nostra privacy policy qui. Puoi accettare i cookies e proseguire, oppure puoi configurare i singoli cookies, utilizzando i tasti qui sotto.</p>
    </article>
    <article class="privacy_article">
        <h2 class="privacy_h2">Privacy Policy</h2>
        <p class="privacy_p">Un cookie è una piccola quantità di dati inviati al tuo browser da un server web e che vengono successivamente memorizzati sul disco fisso del tuo computer. Il cookie viene poi riletto e riconosciuto dal sito web che lo ha inviato ogni qualvolta effettui una connessione successiva. Come parte dei servizi personalizzati per i suoi utenti, il nostro sito utilizza dei cookie per memorizzare e talvolta tenere traccia di alcuni dei dati personali forniti dagli utenti stessi. Ti ricordiamo che il browser è quel software che ti permette di navigare velocemente nella Rete tramite la visualizzazione e il trasferimento delle informazioni sul disco fisso del tuo computer.</p>
    </article>
</section>